import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/custom/navbar";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Beiboot Project SS26",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="de" className={cn(roboto.variable)}>
      <body className={cn(roboto.variable, "font-sans antialiased")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
